### ISSUE TITLE
OSX Bash error twa:212

### ISSUE THREAD

**Issue by rwhitworth** [woodruffw/twa#1]
`xfo=${xfo,,}` on line 212 of twa seems to be causing the error:
`./twa: line 212: ${xfo,,}: bad substitution`

Changing the string to lowercase via`,,` parameter expansion was introduced in Bash version 4 [1] and OSX 10.13 ships with Bash version 3.2.  Is there any chance of changing this to a `tr` or some other method of lower casing characters?

[1] - http://wiki.bash-hackers.org/scripting/bashchanges - listed as 'case modification operators for expansions'

**Comment by woodruffw** [comment]
Thanks for reporting this! Supporting Bash 3 probably isn't on the roadmap -- OS X is the only vendor that I know of that continues to distribute such an ancient version, and Bash 4 provides a bunch of useful string manipulation builtins that future checks will probably use.

Your best bet for using this on OS X is probably to install a modern `bash` via Homebrew (or your preferred package manager).

I'll make a note on the README later today about the version requirement. I'd also accept a PR that adds a sanity check to the script itself, exiting if `$BASH_VERSINFO` (or whatever it is) is insufficient 🙂

**Comment by rwhitworth** [comment]
Fair enough.  Thanks for the fast response and thank you for the utility
