### ISSUE TITLE
error on Line 212

### ISSUE THREAD

**Issue by ElwoodBlues99** [woodruffw/twa#11]
line 212 xfo=${xfo,,} raises a bad substitution error.

It can be commented out.

Also, line 318,[[ "${BASH_VERSINFO[0]}" -ge 4 ]] || die "Expected GNU Bash 4.0 or later, got ${BASH_VERSION}"

should throw a warning, rather than doe. Script works on much earlier BBASH versions.

**Comment by woodruffw** [comment]
Please see #1, #3, #6, and #7. As you saw when you commented the version check out, the script does **not** work on earlier `bash` versions, and probably won't ever.
