### ISSUE TITLE
Incorrect MEH rating on the Strict-Transport-Security test

### ISSUE THREAD

**Issue by Ippo343** [woodruffw/twa#4]
Using twa at commit 30e704b I get an incorrect "MEH" rating on the Strict-Transport-Security test.
However I configured my site to send the `includeSubdomains; preload;` options.

    $ curl -I https://wikipiedi.it
    [...]
    Strict-Transport-Security: max-age=63072000; includeSubdomains; preload;
    [...]

But:

    $ ./twa wikipiedi.it
    Connection to wikipiedi.it 443 port [tcp/https] succeeded!
    PASS(wikipiedi.it): HTTP redirects to HTTPS using a 301
    PASS(wikipiedi.it): max-age is at least 6 months
    MEH(wikipiedi.it): Strict-Transport-Security, but no includeSubDomains
    MEH(wikipiedi.it): Strict-Transport-Security, but no preload

**Comment by woodruffw** [comment]
Thanks for the report! I'll look into this tonight.
