### ISSUE TITLE
Bad substitution error

### ISSUE THREAD

**Issue by ghoffart** [woodruffw/twa#6]
See line `line 212: ${xfo,,}: bad substitution`, something seems to break here.

`./twa  beta.knubbelmac.de
Connection to beta.knubbelmac.de port 443 [tcp/https] succeeded!
MEH(beta.knubbelmac.de): HTTP redirects to HTTPS using a 302
PASS(beta.knubbelmac.de): max-age is at least 6 months
MEH(beta.knubbelmac.de): Strict-Transport-Security, but no includeSubDomains
MEH(beta.knubbelmac.de): Strict-Transport-Security, but no preload
./twa: line 212: ${xfo,,}: bad substitution
PASS(beta.knubbelmac.de): Site sends 'Server', but probably only a vendor ID: Apache
PASS(beta.knubbelmac.de): Site doesn't send 'X-Powered-By'
PASS(beta.knubbelmac.de): Site doesn't send 'Via'
PASS(beta.knubbelmac.de): Site doesn't send 'X-AspNet-Version'
PASS(beta.knubbelmac.de): Site doesn't send 'X-AspNetMvc-Version'
PASS(beta.knubbelmac.de): No SCM repository at: http://beta.knubbelmac.de/.git/HEAD
PASS(beta.knubbelmac.de): No SCM repository at: http://beta.knubbelmac.de/.hg/store/00manifest.i
PASS(beta.knubbelmac.de): No SCM repository at: http://beta.knubbelmac.de/.svn/entries`

**Comment by woodruffw** [comment]
Check out #1 and #3: your copy of `bash` is probably ancient. `twa` requires at least `bash` 4.
